#!/usr/bin/env node
/**
 * Interactive Environment & API Key Setup Wizard for Zero Cost CRM.
 * Run via: `npm run setup:env` or `node scripts/setup-env.mjs`
 */

import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';
import crypto from 'node:crypto';

const ROOT_DIR = process.cwd();
const ENV_LOCAL_PATH = path.join(ROOT_DIR, '.env.local');
const ENV_EXAMPLE_PATH = path.join(ROOT_DIR, '.env.example');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const content = fs.readFileSync(filePath, 'utf8');
  const env = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx !== -1) {
      const key = trimmed.slice(0, eqIdx).trim();
      let val = trimmed.slice(eqIdx + 1).trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      env[key] = val;
    }
  }
  return env;
}

function generateJwtSecret() {
  return crypto.randomBytes(32).toString('hex');
}

async function prompt(rl, question, defaultValue = '') {
  return new Promise((resolve) => {
    const promptText = defaultValue ? `${question} [${defaultValue}]: ` : `${question}: `;
    rl.question(promptText, (answer) => {
      resolve(answer.trim() || defaultValue);
    });
  });
}

async function main() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log('\n============================================================');
  console.log('  ⚡ Zero Cost CRM — Interactive API & Environment Setup ⚡');
  console.log('============================================================\n');

  const existingEnv = parseEnvFile(ENV_LOCAL_PATH);

  // 1. AI Provider & Key
  console.log('--- 1. AI Engine Configuration (Voice STT, OCR & Lead Scoring) ---');
  console.log('Supported Providers:');
  console.log('  1) Groq (Recommended — Ultra-fast Whisper & LLaMA 3.3, generous free tier)');
  console.log('  2) OpenAI (GPT-4o-mini & Whisper-1)');
  console.log('  3) Google Gemini (Gemini 1.5 Flash)');
  console.log('  4) Anthropic (Claude 3.5 Sonnet)');
  console.log('  5) Skip / Mock Mode (Neutral heuristic scoring, no API key needed)\n');

  const providerChoice = await prompt(rl, 'Select AI Provider (1-5)', '1');
  let provider = 'groq';
  let model = 'llama-3.3-70b-versatile';
  let visionModel = 'llama-3.2-11b-vision-preview';
  let whisperModel = 'whisper-large-v3';

  if (providerChoice === '2' || providerChoice.toLowerCase() === 'openai') {
    provider = 'openai';
    model = 'gpt-4o-mini';
    visionModel = 'gpt-4o-mini';
    whisperModel = 'whisper-1';
  } else if (providerChoice === '3' || providerChoice.toLowerCase() === 'gemini') {
    provider = 'gemini';
    model = 'gemini-1.5-flash';
    visionModel = 'gemini-1.5-flash';
    whisperModel = 'gemini-1.5-flash';
  } else if (providerChoice === '4' || providerChoice.toLowerCase() === 'anthropic') {
    provider = 'anthropic';
    model = 'claude-3-5-sonnet-20241022';
    visionModel = 'claude-3-5-sonnet-20241022';
    whisperModel = 'whisper-large-v3';
  } else if (providerChoice === '5' || providerChoice.toLowerCase() === 'mock') {
    provider = 'mock';
  }

  let apiKey = existingEnv.AI_API_KEY || '';
  if (provider !== 'mock') {
    const keyPrompt = provider === 'groq'
      ? 'Enter your Groq API Key (starts with gsk_)'
      : provider === 'openai'
      ? 'Enter your OpenAI API Key (starts with sk-)'
      : provider === 'gemini'
      ? 'Enter your Gemini API Key (starts with AIzaSy)'
      : 'Enter your AI API Key';

    apiKey = await prompt(rl, keyPrompt, apiKey);
  }

  // 2. Database Connection
  console.log('\n--- 2. Database Connection ---');
  const defaultDb = existingEnv.DATABASE_URL || 'postgresql://crm_test:crm_test@localhost:5434/brains_crm_test';
  const databaseUrl = await prompt(rl, 'PostgreSQL DATABASE_URL', defaultDb);

  // 3. Security & Access
  console.log('\n--- 3. Authentication & Access ---');
  const jwtSecret = existingEnv.JWT_SECRET || generateJwtSecret();
  const allowedDomain = await prompt(rl, 'Allowed Email Domain (* for any, or e.g. yourcompany.com)', existingEnv.ALLOWED_EMAIL_DOMAIN || '*');

  // Build new env
  const lines = [
    '# Zero Cost CRM — Generated by npm run setup:env',
    '# Generated at: ' + new Date().toISOString(),
    '',
    `PORT=${existingEnv.PORT || 4000}`,
    `NODE_ENV=${existingEnv.NODE_ENV || 'development'}`,
    `DATABASE_URL=${databaseUrl}`,
    `JWT_SECRET=${jwtSecret}`,
    `ALLOWED_EMAIL_DOMAIN=${allowedDomain}`,
    `CORS_ORIGINS=${existingEnv.CORS_ORIGINS || 'http://localhost:5173,http://localhost:4000'}`,
    `SUBSCRIPTION_PLAN=pro`,
    '',
    '# AI Engine Configuration',
    `AI_PROVIDER=${provider}`,
    `AI_API_KEY=${apiKey}`,
    `AI_MODEL=${model}`,
    `AI_VISION_MODEL=${visionModel}`,
    `AI_WHISPER_MODEL=${whisperModel}`,
    '',
  ];

  fs.writeFileSync(ENV_LOCAL_PATH, lines.join('\n'), 'utf8');

  // Also sync .env for docker compose convenience
  const dotEnvPath = path.join(ROOT_DIR, '.env');
  fs.writeFileSync(dotEnvPath, lines.join('\n'), 'utf8');

  console.log('\n============================================================');
  console.log('  ✅ Configuration successfully written to .env.local & .env');
  console.log('============================================================');
  console.log(`\n  • AI Provider:      ${provider.toUpperCase()} (${apiKey ? 'Key configured' : 'Mock/No key'})`);
  console.log(`  • Database URL:     ${databaseUrl}`);
  console.log(`  • Allowed Domains:  ${allowedDomain}`);
  console.log(`  • Active Plan:      PRO (Full AI quotas unlocked)`);
  console.log('\nTo launch your CRM:');
  console.log('  npm run dev          # Start local dev server');
  console.log('  docker compose restart crm # If running via Docker\n');

  rl.close();
}

main().catch((err) => {
  console.error('\nSetup wizard error:', err);
  process.exit(1);
});
